### ISSUE TITLE
Unknow class issue 

### ISSUE THREAD

**Issue by nirajketan** [mirasvit/module-blog-sample-data#1]
![image](https://cloud.githubusercontent.com/assets/12871321/14437766/72efedaa-0040-11e6-80a9-111dfc059bb0.png)

\Faker\Factory unknown class found.

**Comment by adrok** [comment]
Did you installed module using composer?

https://github.com/mirasvit/module-blog-sample-data/blob/master/composer.json
sample-data composer.json require this library "fzaninotto/faker"
